branch-defaults:
  development-2:
    environment: educative-symfony-dev2
environment-defaults:
  educative-symfony-dev2:
    branch: null
    repository: null
global:
  application_name: educative-symfony
  default_ec2_keyname: null
  default_platform: PHP 8.1 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
